version: '3'
services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube_sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonar
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
  postgres: 
    image: postgres:11
    container_name: sonarqube_postgres
    restart: always
    ports:  
     - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar 
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata:
  sonar_conf:
  sonar_data:
  sonar_extensions:
